version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - ./app:/var/www/app
            - ./config:/var/www/config
            - ./resources:/var/www/resources
            - ./routes:/var/www/routes
            - ./storage:/var/www/storage
            - ./tests:/var/www/tests
            - .env:/var/www/.env
        depends_on:
            - postgres
            # - redis

    web:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "3000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public/index.php:/var/www/public/index.php
            - ./public/favicon.ico:/var/www/public/favicon.ico
            - ./public/robots.txt:/var/www/public/robots.txt
        depends_on:
            - app

    postgres:
        image: postgres:latest
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432" # Exposes PostgreSQL on port 5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
    # redis:
    #     image: redis:latest
    #     container_name: laravel_redis
    #     restart: always
    #     ports:
    #         - "6379:6379"

volumes:
    postgres_data:
        driver: local
